In [25]:
import pandas as pd
import numpy as np
import seaborn as sns

import sys
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
np.set_printoptions(threshold=sys.maxsize)

%matplotlib inline

In [37]:
train_values = pd.read_csv('data/train_values.csv', index_col='building_id')
train_labels = pd.read_csv('data/train_labels.csv', index_col='building_id')
train = train_values.merge(train_labels, left_index=True, right_index=True)
train.sort_index(inplace=True)
train.head()

             geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  age  area_percentage  height_percentage land_surface_condition foundation_type roof_type ground_floor_type other_floor_type position plan_configuration  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other legal_ownership_status  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other  damage_grade
building_id
4                        30             266            1224                    1   25                5                  2                      t               r         n                 f                j        s                  d                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                      v               0                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2
8                        17             409           12182                    2    0               13                  7                      t               r         n                 f                q        s                  d                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                      v               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             3
12                       17             716            7056                    2    5               12                  6                      o               r         q                 f                q        s                  d                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                      v               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             3
16                        4             651             105                    2   80                5                  4                      n               r         n                 f                q        s                  d                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                      v               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2
17                        3            1387            3909                    5   40                5                 10                      t               r         n                 f                q        o                  d                             0                                    0                              0                                       0                                    1                                       0                          0                          0                                     0                                 0                         0                      v               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2

In [24]:
train.groupby(by=['damage_grade']).count().iloc[:,0]

damage_grade
1     25124
2    148259
3     87218
Name: geo_level_1_id, dtype: int64

In [32]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260601 entries, 802906 to 747594
Data columns (total 39 columns):
geo_level_1_id                            260601 non-null int64
geo_level_2_id                            260601 non-null int64
geo_level_3_id                            260601 non-null int64
count_floors_pre_eq                       260601 non-null int64
age                                       260601 non-null int64
area_percentage                           260601 non-null int64
height_percentage                         260601 non-null int64
land_surface_condition                    260601 non-null object
foundation_type                           260601 non-null object
roof_type                                 260601 non-null object
ground_floor_type                         260601 non-null object
other_floor_type                          260601 non-null object
position                                  260601 non-null object
plan_configuration                        260601 non-null object
has_superstructure_adobe_mud              260601 non-null int64
has_superstructure_mud_mortar_stone       260601 non-null int64
has_superstructure_stone_flag             260601 non-null int64
has_superstructure_cement_mortar_stone    260601 non-null int64
has_superstructure_mud_mortar_brick       260601 non-null int64
has_superstructure_cement_mortar_brick    260601 non-null int64
has_superstructure_timber                 260601 non-null int64
has_superstructure_bamboo                 260601 non-null int64
has_superstructure_rc_non_engineered      260601 non-null int64
has_superstructure_rc_engineered          260601 non-null int64
has_superstructure_other                  260601 non-null int64
legal_ownership_status                    260601 non-null object
count_families                            260601 non-null int64
has_secondary_use                         260601 non-null int64
has_secondary_use_agriculture             260601 non-null int64
has_secondary_use_hotel                   260601 non-null int64
has_secondary_use_rental                  260601 non-null int64
has_secondary_use_institution             260601 non-null int64
has_secondary_use_school                  260601 non-null int64
has_secondary_use_industry                260601 non-null int64
has_secondary_use_health_post             260601 non-null int64
has_secondary_use_gov_office              260601 non-null int64
has_secondary_use_use_police              260601 non-null int64
has_secondary_use_other                   260601 non-null int64
damage_grade                              260601 non-null int64
dtypes: int64(31), object(8)
memory usage: 89.5+ MB

In [33]:
train.describe()

       geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq            age  area_percentage  height_percentage  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other   damage_grade
count   260601.000000   260601.000000   260601.000000        260601.000000  260601.000000    260601.000000      260601.000000                 260601.000000                        260601.000000                  260601.000000                           260601.000000                        260601.000000                           260601.000000              260601.000000              260601.000000                         260601.000000                     260601.000000             260601.000000   260601.000000      260601.000000                  260601.000000            260601.000000             260601.000000                  260601.000000             260601.000000               260601.000000                  260601.000000                 260601.000000                 260601.000000            260601.000000  260601.000000
mean        13.900353      701.074685     6257.876148             2.129723      26.535029         8.018051           5.434365                      0.088645                             0.761935                       0.034332                                0.018235                             0.068154                                0.075268                   0.254988                   0.085011                              0.042590                          0.015859                  0.014985        0.983949           0.111880                       0.064378                 0.033626                  0.008101                       0.000940                  0.000361                    0.001071                       0.000188                      0.000146                      0.000088                 0.005119       2.238272
std          8.033617      412.710734     3646.369645             0.727665      73.565937         4.392231           1.918418                      0.284231                             0.425900                       0.182081                                0.133800                             0.252010                                0.263824                   0.435855                   0.278899                              0.201931                          0.124932                  0.121491        0.418389           0.315219                       0.245426                 0.180265                  0.089638                       0.030647                  0.018989                    0.032703                       0.013711                      0.012075                      0.009394                 0.071364       0.611814
min          0.000000        0.000000        0.000000             1.000000       0.000000         1.000000           2.000000                      0.000000                             0.000000                       0.000000                                0.000000                             0.000000                                0.000000                   0.000000                   0.000000                              0.000000                          0.000000                  0.000000        0.000000           0.000000                       0.000000                 0.000000                  0.000000                       0.000000                  0.000000                    0.000000                       0.000000                      0.000000                      0.000000                 0.000000       1.000000
25%          7.000000      350.000000     3073.000000             2.000000      10.000000         5.000000           4.000000                      0.000000                             1.000000                       0.000000                                0.000000                             0.000000                                0.000000                   0.000000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                       0.000000                  0.000000                    0.000000                       0.000000                      0.000000                      0.000000                 0.000000       2.000000
50%         12.000000      702.000000     6270.000000             2.000000      15.000000         7.000000           5.000000                      0.000000                             1.000000                       0.000000                                0.000000                             0.000000                                0.000000                   0.000000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                       0.000000                  0.000000                    0.000000                       0.000000                      0.000000                      0.000000                 0.000000       2.000000
75%         21.000000     1050.000000     9412.000000             2.000000      30.000000         9.000000           6.000000                      0.000000                             1.000000                       0.000000                                0.000000                             0.000000                                0.000000                   1.000000                   0.000000                              0.000000                          0.000000                  0.000000        1.000000           0.000000                       0.000000                 0.000000                  0.000000                       0.000000                  0.000000                    0.000000                       0.000000                      0.000000                      0.000000                 0.000000       3.000000
max         30.000000     1427.000000    12567.000000             9.000000     995.000000       100.000000          32.000000                      1.000000                             1.000000                       1.000000                                1.000000                             1.000000                                1.000000                   1.000000                   1.000000                              1.000000                          1.000000                  1.000000        9.000000           1.000000                       1.000000                 1.000000                  1.000000                       1.000000                  1.000000                    1.000000                       1.000000                      1.000000                      1.000000                 1.000000       3.000000

In [44]:
from sklearn.preprocessing import LabelEncoder

In [43]:
df_enc = train.copy()
for col in train.select_dtypes(object).columns:
    df_enc[col] = LabelEncoder().fit_transform(train[col].values.reshape(-1,1))

/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

             geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  age  area_percentage  height_percentage  land_surface_condition  foundation_type  roof_type  ground_floor_type  other_floor_type  position  plan_configuration  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other  legal_ownership_status  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other  damage_grade
building_id
4                        30             266            1224                    1   25                5                  2                       2                2          0                  0                 0         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               0                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2
8                        17             409           12182                    2    0               13                  7                       2                2          0                  0                 1         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             3
12                       17             716            7056                    2    5               12                  6                       1                2          1                  0                 1         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             3
16                        4             651             105                    2   80                5                  4                       0                2          0                  0                 1         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2
17                        3            1387            3909                    5   40                5                 10                       2                2          0                  0                 1         1                   2                             0                                    0                              0                                       0                                    1                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2

In [47]:
df_enc.head()

             geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  age  area_percentage  height_percentage  land_surface_condition  foundation_type  roof_type  ground_floor_type  other_floor_type  position  plan_configuration  has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  has_superstructure_mud_mortar_brick  has_superstructure_cement_mortar_brick  has_superstructure_timber  has_superstructure_bamboo  has_superstructure_rc_non_engineered  has_superstructure_rc_engineered  has_superstructure_other  legal_ownership_status  count_families  has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  has_secondary_use_rental  has_secondary_use_institution  has_secondary_use_school  has_secondary_use_industry  has_secondary_use_health_post  has_secondary_use_gov_office  has_secondary_use_use_police  has_secondary_use_other  damage_grade
building_id
4                        30             266            1224                    1   25                5                  2                       2                2          0                  0                 0         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               0                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2
8                        17             409           12182                    2    0               13                  7                       2                2          0                  0                 1         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             3
12                       17             716            7056                    2    5               12                  6                       1                2          1                  0                 1         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             3
16                        4             651             105                    2   80                5                  4                       0                2          0                  0                 1         2                   2                             0                                    1                              0                                       0                                    0                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2
17                        3            1387            3909                    5   40                5                 10                       2                2          0                  0                 1         1                   2                             0                                    0                              0                                       0                                    1                                       0                          0                          0                                     0                                 0                         0                       2               1                  0                              0                        0                         0                              0                         0                           0                              0                             0                             0                        0             2

In [46]:
#sns.pairplot(df_enc, hue='damage_grade')

# Model - TODO scale + distribution +xgboost + tuning

In [53]:
from sklearn.preprocessing import MinMaxScaler

numpy.ndarray

In [52]:
scaler = MinMaxScaler()
df_enc = scaler.fit_transform(df_enc)
df_enc.head()

/root/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [ ]:
import xgboost as xgb